// <auto-generated />
using System;
using Issue.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Issue.Persistence.Context.Migrations
{
    [DbContext(typeof(IssueDbContext))]
    [Migration("20260812150320_Initial123")]
    partial class Initial123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Issue.Domain.Entities.Issue.AiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepairSteps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("AiAnalysis");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.ExpertReviews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("ExpertReviews");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.GPSLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GPSLocation");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedExpertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("GPSLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GPSLocationId")
                        .IsUnique();

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.IssueAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueAttachment");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.IssueFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.ToTable("issueFeedbacks");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.MaintenanceTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTeams");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RelatedIssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedIssueId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.RepairSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FarmerNotified")
                        .HasColumnType("bit");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("SlotEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("SlotStart")
                        .HasColumnType("time");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("RepairSchedules");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.ResolutionActions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("TeamId");

                    b.ToTable("ResolutionActions");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("StatusHistories");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.AiAnalysis", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.Issue", null)
                        .WithMany("AiAnalyses")
                        .HasForeignKey("IssueId");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.Comment", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.ExpertReviews", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.Issue", "Issue")
                        .WithMany("ExpertReviews")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.Issue", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.GPSLocation", "GPSLocation")
                        .WithOne("Issue")
                        .HasForeignKey("Issue.Domain.Entities.Issue.Issue", "GPSLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GPSLocation");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.IssueAttachment", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.Issue", "Issue")
                        .WithMany("IssueAttachments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.IssueFeedback", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.Issue", "Issue")
                        .WithOne("Feedback")
                        .HasForeignKey("Issue.Domain.Entities.Issue.IssueFeedback", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.Notification", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.Issue", "RelatedIssue")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedIssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedIssue");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.RepairSchedule", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.Issue", "Issue")
                        .WithOne("RepairSchedule")
                        .HasForeignKey("Issue.Domain.Entities.Issue.RepairSchedule", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Issue.Domain.Entities.Issue.MaintenanceTeam", "Team")
                        .WithMany("RepairSchedules")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Issue");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.ResolutionActions", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.Issue", "Issue")
                        .WithMany("ResolutionActions")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Issue.Domain.Entities.Issue.MaintenanceTeam", "Team")
                        .WithMany("ResolutionActions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Issue");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.StatusHistory", b =>
                {
                    b.HasOne("Issue.Domain.Entities.Issue.Issue", "Issue")
                        .WithMany("StatusHistory")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.GPSLocation", b =>
                {
                    b.Navigation("Issue")
                        .IsRequired();
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.Issue", b =>
                {
                    b.Navigation("AiAnalyses");

                    b.Navigation("Comments");

                    b.Navigation("ExpertReviews");

                    b.Navigation("Feedback");

                    b.Navigation("IssueAttachments");

                    b.Navigation("Notifications");

                    b.Navigation("RepairSchedule");

                    b.Navigation("ResolutionActions");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Issue.Domain.Entities.Issue.MaintenanceTeam", b =>
                {
                    b.Navigation("RepairSchedules");

                    b.Navigation("ResolutionActions");
                });
#pragma warning restore 612, 618
        }
    }
}
