<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\CommanLib\CommanLib\CommanLib.csproj" />
    <ProjectReference Include="..\..\Core\ServiceAbsraction\ServiceAbsraction.csproj" />
    <ProjectReference Include="..\..\Core\Service\Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
