<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.3" />
    <PackageReference Include="MassTransit" Version="8.3.6" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Issue.Client\Issue.Client.csproj" />
    <ProjectReference Include="..\Issue.Domain\Issue.Domain.csproj" />
    <ProjectReference Include="..\Issue.ServiceAbstraction\Issue.ServiceAbstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DependencyInjection\" />
  </ItemGroup>

</Project>
